EXEC sp_resetstatus [SUSDB];
ALTER DATABASE [SUSDB] SET EMERGENCY
DBCC checkdb([SUSDB])
ALTER DATABASE [SUSDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DBCC CheckDB ([SUSDB], REPAIR_ALLOW_DATA_LOSS)
ALTER DATABASE [SUSDB] SET MULTI_USER